#!/usr/bin/env bash

set -eu -o pipefail
trap 'echo "ERROR: line no = $LINENO, exit status = $?" >&2; exit 1' ERR

input=$1

texFile=${input%.*}.tex
dviFile=${input%.*}.dvi
pdfFile=${input%.*}.pdf


platex ${texFile}
dvipdfmx ${dviFile}
rm -rf *.dvi *.aux *.log
evince ${pdfFile}
